### ISSUE TITLE
Using Bcrypt Without Salt

### ISSUE THREAD

**Issue by EliterScripts** [mikejsavage/lua-bcrypt#12]
I really need to use bcrypt without using a salt. I have a particular project that needs hashes without a salt. Is that possible?

**Comment by mikejsavage** [comment]
It isn’t and I don’t want to support that because the library is meant to provide the minimal API for password hashing.

There are more general purpose libraries for other algorithms like scrypt and argon2 which might provide what you want.

If you really need bcrypt then email me and we can discuss possible solutions
